local distributionTable = VehicleDistributions[1]
if VehicleDistributions then

	VehicleDistributions.CostumesVan = {
		TruckBed =
		{
			rolls = 4,
			items = {
				"FrikiItems.VaderHelmet", 2,
				"FrikiItems.VaderCape",2,
				"FrikiItems.VaderSkirt",2,
				"FrikiItems.VaderBoots",2,
				"FrikiItems.VaderGloves",2,
				"FrikiItems.SurveyCorpsClassicShirt2",2,
				"FrikiItems.SurveyCorpsClassicBoots",2,
				"FrikiItems.SurveyCorpsClassicShort",2,
				"FrikiItems.SurveyCorpsClassicPants",2,
				"FrikiItems.SurveyCorpsClassicShirt",2,
				"FrikiItems.SurveyCorpsClassicJacket",2,
				"FrikiItems.VaderShirt",2,
				"FrikiItems.TarManShoes",2,
				"FrikiItems.TarManPants",2,
				"FrikiItems.TarManGloves",2,
				"FrikiItems.TarManMask",2,
				"FrikiItems.TarMan",2,
				"FrikiItems.BruceLee",2,
				"FrikiItems.Elza",2,
				"FrikiItems.HevBoots",2,
				"FrikiItems.HevGloves",2,
				"FrikiItems.HevPants",2,
				"FrikiItems.HevShirt",2,
				"FrikiItems.HevVest",2,
				"FrikiItems.SurveyCorpsBody",2,
				"FrikiItems.SlendermanMask",2,
				"FrikiItems.SurveyCorps",2,
				"FrikiItems.MarioBrosShirt",2,
				"FrikiItems.MarioBrosPlate",2,
				"FrikiItems.MarioBrosCap",2,
				"FrikiItems.SpidermanMask",2,
				"FrikiItems.SpidermanGloves",2,
				"FrikiItems.SpidermanBoots",2,
				"FrikiItems.SpidermanPants",2,
				"FrikiItems.SpidermanBody",2,
				"FrikiItems.GokuHairWig",2,
				"FrikiItems.GokuSuit",2,
				"FrikiItems.GokuBoots",2,
				"FrikiItems.GokuLongShirt",2,
				"FrikiItems.SupermanCape",2,
				"FrikiItems.SupermanSuit",2,
				"FrikiItems.SupermanBoots",2,
				"FrikiItems.DeadpoolBody",2,
				"FrikiItems.DeadpoolMask",2,
				"FrikiItems.DeadpoolPants",2,
				"FrikiItems.DeadpoolBoots",2,
				"FrikiItems.DeadpoolGloves",2,
				"FrikiItems.DeadpoolKatana",2,
				"FrikiItems.PyramidHeadHelmet",2,
				"FrikiItems.PyramidHeadDress",2,
				"FrikiItems.PyramidHeadBoots",2,
				"FrikiItems.PyramidHeadGloves",2,
				"FrikiItems.ElChavoHat",2,
				"FrikiItems.Elchavo_shirt",2,
				"FrikiItems.Elchavo_Short",2,
				"FrikiItems.Fantastic4Body",2,
				"FrikiItems.Fantastic4Boots",2,
				"FrikiItems.Fantastic4Gloves",2,
				"FrikiItems.HanSoloVest",2,
				"FrikiItems.HanSoloShirt",2,
				"FrikiItems.HanSoloPants",2,
				"FrikiItems.HanSoloBoots",2,
				"FrikiItems.SpidermanBodyBlack",2,
				"FrikiItems.SpidermanPantsBlack",2,
				"FrikiItems.SpidermanBootsBlack",2,
				"FrikiItems.SpidermanGlovesBlack",2,
				"FrikiItems.SpidermanMaskBlack",2,
				"FrikiItems.TheIncrediblesMask",2,
				"FrikiItems.TheIncrediblesBody",2,
			},
			junk = {
				rolls = 4,
				items = {
					"FrikiItems.VaderHelmet", 2,
					"FrikiItems.VaderCape",2,
					"FrikiItems.VaderSkirt",2,
					"FrikiItems.VaderBoots",2,
					"FrikiItems.VaderGloves",2,
					"FrikiItems.SurveyCorpsClassicShirt2",2,
					"FrikiItems.SurveyCorpsClassicBoots",2,
					"FrikiItems.SurveyCorpsClassicShort",2,
					"FrikiItems.SurveyCorpsClassicPants",2,
					"FrikiItems.SurveyCorpsClassicShirt",2,
					"FrikiItems.SurveyCorpsClassicJacket",2,
					"FrikiItems.VaderShirt",2,
					"FrikiItems.TarManShoes",2,
					"FrikiItems.TarManPants",2,
					"FrikiItems.TarManGloves",2,
					"FrikiItems.TarManMask",2,
					"FrikiItems.TarMan",2,
					"FrikiItems.BruceLee",2,
					"FrikiItems.Elza",2,
					"FrikiItems.HevBoots",2,
					"FrikiItems.HevGloves",2,
					"FrikiItems.HevPants",2,
					"FrikiItems.HevShirt",2,
					"FrikiItems.HevVest",2,
					"FrikiItems.SurveyCorpsBody",2,
					"FrikiItems.SlendermanMask",2,
					"FrikiItems.SurveyCorps",2,
					"FrikiItems.MarioBrosShirt",2,
					"FrikiItems.MarioBrosPlate",2,
					"FrikiItems.MarioBrosCap",2,
					"FrikiItems.SpidermanMask",2,
					"FrikiItems.SpidermanGloves",2,
					"FrikiItems.SpidermanBoots",2,
					"FrikiItems.SpidermanPants",2,
					"FrikiItems.SpidermanBody",2,
					"FrikiItems.GokuHairWig",2,
					"FrikiItems.GokuSuit",2,
					"FrikiItems.GokuBoots",2,
					"FrikiItems.GokuLongShirt",2,
					"FrikiItems.SupermanCape",2,
					"FrikiItems.SupermanSuit",2,
					"FrikiItems.SupermanBoots",2,
					"FrikiItems.DeadpoolBody",2,
					"FrikiItems.DeadpoolMask",2,
					"FrikiItems.DeadpoolPants",2,
					"FrikiItems.DeadpoolBoots",2,
					"FrikiItems.DeadpoolGloves",2,
					"FrikiItems.DeadpoolKatana",2,
					"FrikiItems.PyramidHeadHelmet",2,
					"FrikiItems.PyramidHeadDress",2,
					"FrikiItems.PyramidHeadBoots",2,
					"FrikiItems.PyramidHeadGloves",2,
					"FrikiItems.ElChavoHat",2,
					"FrikiItems.Elchavo_shirt",2,
					"FrikiItems.Elchavo_Short",2,
					"FrikiItems.Fantastic4Body",2,
					"FrikiItems.Fantastic4Boots",2,
					"FrikiItems.Fantastic4Gloves",2,
					"FrikiItems.HanSoloVest",2,
					"FrikiItems.HanSoloShirt",2,
					"FrikiItems.HanSoloPants",2,
					"FrikiItems.HanSoloBoots",2,
					"FrikiItems.SpidermanBodyBlack",2,
					"FrikiItems.SpidermanPantsBlack",2,
					"FrikiItems.SpidermanBootsBlack",2,
					"FrikiItems.SpidermanGlovesBlack",2,
					"FrikiItems.SpidermanMaskBlack",2,
					"FrikiItems.TheIncrediblesMask",2,
					"FrikiItems.TheIncrediblesBody",2,
				}
			}
		},
		GloveBox = {
			rolls = 2,
			items = {
				"Headphones", 20,
				"Headphones", 20,
				"Disc_Retail", 20,
				"Disc_Retail", 20,
				"Disc_Retail", 20,
				"Disc_Retail", 20,
				"Disc_Retail", 20,
				"Cigarettes", 20,
				"Lighter", 4,
				"Matches", 8,
				"Bullets28Box", 20,
				"Revolver_Short", 20,
				"WhiskeyFull", 20,
				"Money", 20,
				"HottieZ", 20,
				"Tissue", 20,
				"Tissue", 20,
				"Radio.CDplayer", 2,
				"Toothbrush",2,
				"Scotchtape", 4,
				"SheetPaper2", 20,
			},
			junk = {
				rolls = 2,
				items = {
					"Headphones", 20,
					"Headphones", 20,
					"Disc_Retail", 20,
					"Disc_Retail", 20,
					"Disc_Retail", 20,
					"Disc_Retail", 20,
					"Disc_Retail", 20,
					"Cigarettes", 20,
					"Lighter", 4,
					"Matches", 8,
					"Bullets28Box", 20,
					"Revolver_Short", 20,
					"WhiskeyFull", 20,
					"Money", 20,
					"HottieZ", 20,
					"Tissue", 20,
					"Tissue", 20,
					"Radio.CDplayer", 2,
					"Toothbrush",2,
					"Scotchtape", 4,
					"SheetPaper2", 20,
				}
			}
		},
	}
end

pmrmcustomdist = {
	-- CostumesVan
    CostumesVan = { 
		Normal = VehicleDistributions.CostumesVan; 
	},
};

distributionTable["CostumesVan"] = pmrmcustomdist["CostumesVan"]